# Generated by Django 5.0.7 on 2024-08-31 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama', models.CharField(max_length=75)),
                ('tmp_lahir', models.CharField(max_length=150)),
                ('tgl_lahir', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('no_hp', models.IntegerField(blank=True, null=True)),
                ('img_user', models.ImageField(blank=True, default='profile.png', upload_to='users/')),
                ('is_actice', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
